# Generated by Django 4.2 on 2024-01-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifications',
            name='type',
        ),
        migrations.AddField(
            model_name='modifications',
            name='type',
            field=models.ManyToManyField(blank=True, to='store.modificationtype'),
        ),
    ]
