# Generated by Django 4.2 on 2023-12-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_Called',
            field=models.BooleanField(default=False),
        ),
    ]
