# Generated by Django 4.2 on 2023-12-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_feedback_is_called'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ОЧІКУЄТЬСЯ', 'ОЧІКУЄТЬСЯ'), ('В ОБРОБЦІ', 'В ОБРОБЦІ'), ('ВИКОНАНО', 'ВИКОНАНО')], default='ОЧІКУЄТЬСЯ', max_length=50),
        ),
    ]
